name: .NET Core Desktop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Change working directory
        run: Set-Location -Path 'D:\a\PteroController\PteroController'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration ${{ matrix.configuration }}
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }}
        env:
          Configuration: ${{ matrix.configuration }}
