name: .NET Core Desktop

on:
  push:
    branches: [ "v2develop" ]
  pull_request:
    branches: [ "v2develop" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  
                            
    env:
      Solution_Name: PteroController.sln                         

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test PteroController.csproj

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore and build the application
      run: dotnet build PteroController.csproj
      env:
        Configuration: ${{ matrix.configuration }}
