name: .NET Core Desktop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Restore NuGet packages
        run: msbuild PteroController.sln /t:Restore

      - name: Build the project
        run: msbuild PteroController.sln /p:Configuration=Release

      - name: Run tests
        run: msbuild PteroController.sln /t:Test /p:Configuration=Release
